### ISSUE TITLE
Add Prometheus to helm installation

### ISSUE THREAD

**Issue by jdenen** [inhindsight/hindsight#116]
We've added `telemetry` events to some places in the system and will be adding more (#93), but we'll need some place to collect them. Prometheus makes the most sense to start with.

- [x] Prometheus is installed by default with Hindsight
  - [x] Can be toggled off via `helm` flag
- [x] Prometheus scrapes `telemetry` metrics from Hindsight services producing them

**Comment by jeffgrunewald** [comment]
implemented (primarily) by the following: 
https://github.com/inhindsight/hindsight/pull/185
https://github.com/inhindsight/hindsight/pull/200
